version: '2.0'
services:
  redis:
    image: redis:5.0.7
    container_name: seatable-thumbnail-redis
    networks:
      - seatable-thumbnail-net

  seatable:
    image: docker.seafile.top/seafile-dev/seatable-thumbnail-server:2.1.1
    container_name: seatable-thumbnail
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/seatable-thumbnail/shared:/shared
    environment:
      - SEATABLE_THUMBNAIL_SERVER_HOSTNAME=thumbnail.seatable.cn
      - SEATABLE_THUMBNAIL_SERVER_LETSENCRYPT=True
    depends_on:
      - redis
    networks:
      - seatable-thumbnail-net

networks:
  seatable-thumbnail-net:
